[package]
name = "wal-rust"
version = "0.1.0"
authors = ["samparsky <8148384+samparsky@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"